### ISSUE TITLE
Change the title of the website

### ISSUE THREAD

**Issue by utpalendubarman** [utpalendubarman/youtube-downloader#1]
Change the title of the website in the title bar

**Comment by Jwright707** [comment]
I would like to work on this issue. Would you like the title of the site to be called Youtube Downloader?

**Comment by utpalendubarman** [comment]
@Jwright707 This project is for JWOC Competition

**Comment by sneha-baser** [comment]
@utpalendubarman i want to resolve this issue . could you please assign me
