### ISSUE TITLE
add menus in navigation section

### ISSUE THREAD

**Issue by utpalendubarman** [utpalendubarman/youtube-downloader#4]
Add 3 menus:- downloader, about, contributors in the navigation bar

**Comment by luckykumarirai** [comment]
I would like to contribute to this issue as a participant of JWoC.

**Comment by Niveditha18** [comment]
I would like to contribute to this issue.

**Comment by anushruti11** [comment]
I would like to work on this.

**Comment by sneha-baser** [comment]
as per instructions on taking up the issue on 21th Jan (Under JWOC), I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by utpalendubarman** [comment]
@sneha-baser I have assigned you another issue, please maintain the serial
