### ISSUE TITLE
add react-router-dom for page routing

### ISSUE THREAD

**Issue by utpalendubarman** [utpalendubarman/youtube-downloader#5]

**Comment by MeerHamza1421** [comment]
I want to work on some issues

**Comment by utpalendubarman** [comment]
@MeerHamza1421 This project is for JWOC competition

**Comment by MeerHamza1421** [comment]
Oh sorry 😅

**Comment by sneha-baser** [comment]
@utpalendubarman   I wanna work on this issue and resolve . could you please assign me.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue @utpalendubarman ! Assign it to me if it's free! I'm from Jwoc

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue @utpalendubarman ! Assign it to me once the coding period starts (jwoc).
