### ISSUE TITLE
fetch data from server for video downloading

### ISSUE THREAD

**Issue by utpalendubarman** [utpalendubarman/youtube-downloader#6]

**Comment by noob-26** [comment]
I want to work on this issue. I have some experience using fetch() API in JavaScript. Can you please assign me?

**Comment by sneha-baser** [comment]
as per instructions on taking up the issue on 21th Jan (Under JWOC), I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue! Kindly assign it to me @utpalendubarman !
