### ISSUE TITLE
add a footer 

### ISSUE THREAD

**Issue by utpalendubarman** [utpalendubarman/youtube-downloader#9]

**Comment by sneha-baser** [comment]
@utpalendubarman  I wanna work on this issue and resolve . could you please assign me.

**Comment by magjoy6** [comment]
I would like to fix this issue.

**Comment by magjoy6** [comment]
@utpalendubarman bhaiya

**Comment by Niveditha18** [comment]
I would like to contribute to this issue.

**Comment by sneha-baser** [comment]
as per instructions on taking up the issue on 21th Jan (Under JWOC), I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by anushruti11** [comment]
I would like to work on this issue.

**Comment by utpalendubarman** [comment]
@anushruti11 Go ahead
